---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# My project

<!-- badges: start -->
<!-- badges: end -->

Repo of ....


Project uses `{targets}`and `{renv}` and `{here}`. See `Howto` section for details

`data\` : contains raw data ...

`code\` : functions called by `_targets.R` in `here::here("code", "targets_functions"))`

`reports\`: output files.

# Howto 

The pipeline uses `{targets}` (https://books.ropensci.org/targets/) and is setup to run in parallel on SLURM (with `{future.batchtools}`).
The files `batchtools.slurm.tmpl` and `.batchtools.conf.R` are configuration files used by the API `{future.batchtools}`  to communicate with SLURM. Insert path to your home directory in `.batchtools.conf.R` and copy `batchtools.slurm.tmpl`
to you home directory.

Resources to deploy for each target are specified in the file `_targets_resources.conf.R` that is sourced in the 
main `_targets.R` file.

Use `targets::tar_make_future(workers = 10)` from inside `srun` interactive session or run `sbatch start_targets.sh` to initiate the pipeline. The job `master` will control the execution of the other jobs. 

SLURM Logs are created in `log/` (be sure to have a folder with that name in the current directory).

A reproducible R environment is maintained using `{renv}` (`renv.lock`).


## Set Up

Initialize and install packages with:

```
renv::restore()
```

Run the pipeline.

```
targets::tar_make()
# or targets::tar_make_future(workers = 10)
```

Check manifest with `targets::tar_manifest()` and Load targets with `targets::tar_load("name_of_target)`


